services:
  - type: web
    name: stagett
    env: docker
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - fromGroup: stagett-env
databases:
  - name: stagett-db
    databaseName: stagett
    user: stagett
    plan: starter
